import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import AchievementCard from "../Components/Home/AchievementCard";
import InventoryCard from "../Components/Home/InventoryCard";
import ProfileCard from "../Components/Home/ProfileCard";

const Home: NextPage = () => {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <main>
        <div className=" flex px-12 py-6 md:w-10/12 md:ml-6 w-full ">
          <ProfileCard></ProfileCard>
        </div>
        <div className=" grid grid-cols-1 md:grid-cols-2 gap-6 mx-6">
          <div className="">
            <AchievementCard></AchievementCard>
          </div>
          <div className="">
            <InventoryCard></InventoryCard>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
